CREATE TABLE IF NOT EXISTS Line(
 InvoiceID INT,
 ProductID VARCHAR(10),
 LineNumber INT NOT NULL,
 PriceBy VARCHAR(30) NOT NULL,
 Price DECIMAL(10,2) NOT NULL,
 Quantity INT NOT NULL,
 SubTotal DECIMAL(10,2) DEFAULT 0.0,
 Discount DECIMAL(5,2) DEFAULT 0.0,
 NetTotal DECIMAL(10,2) DEFAULT 0.0,
 PRIMARY KEY (InvoiceID, ProductID, PriceBy),
 FOREIGN KEY (InvoiceID) REFERENCES Invoice(InvoiceID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE ON UPDATE CASCADE
);